services:
  - type: web
    name: agent-medical-backend-simple
    env: python
    region: frankfurt # Choisissez la région la plus proche de vous
    plan: free # Utilise le plan gratuit de Render
    buildCommand: "pip install -r requirements.txt"
    # MISE À JOUR : La commande pointe maintenant vers main.py au lieu de app/main.py
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: GEMINI_API_KEY
        fromSecret: true
      - key: SERPER_API_KEY
        fromSecret: true
      - key: FIRECRAWL_API_KEY
        fromSecret: true
